apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-cloud-databases-redis-operator-v1.5-ibm-operator-catalog-openshift-marketplace
  namespace: lifecycle-manager
spec:
  channel: v1.5
  installPlanApproval: Automatic
  name: ibm-cloud-databases-redis-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-cloud-databases-redis.v1.5.1
